Extracted api into mycelium-api crate
threefoldtech/mycelium pull request #276
Opened 2024-05-30 15:53 UTC by maximevanhees

2024-05-30 16:37 UTC, LeeSmet commented
@maximevanhees it looks like the changes to myceliumd-private aren't included in the commit

2024-05-30 19:22 UTC, maximevanhees commented
@LeeSmet, thanks! I've added the files in the latest commit.

2024-05-30 20:48 UTC, LeeSmet requested changes
Single comment, additionally the lock file of myceliumd-private is not updated. This can be done by just building the binary and then committing the new lock file.

2024-05-30 20:48 UTC, LeeSmet commented on mycelium-api/Cargo.toml
> +edition = "2021"
This is missing the `license-file` and `readme` keys (both can link to the parent directory files, similar to other crates)

2024-05-31 06:53 UTC, maximevanhees commented
Should be good now.

2024-05-31 07:33 UTC, LeeSmet approved these changes

2024-05-31 07:34 UTC, merged