Mycelium UI
threefoldtech/mycelium pull request #385
Opened 2024-08-13 12:30 UTC by maximevanhees

Related to #340

At this moment the Dioxus GUI offers the following:
- Changing API server address
- Viewing/searching connected peers
- Viewing rx and tx data flow of a specific peer
- Viewing/searching selected and fallback routes

TODO:
- Adding/removing peers
- Rebranding application to be more "in theme" with Threefold design

Some screenshots:
![Screenshot_20240813_142710](https://github.com/user-attachments/assets/4db8accd-5b5f-491b-a14d-87c28e9888d0)
![Screenshot_20240813_142826](https://github.com/user-attachments/assets/b80ef80e-77d4-4929-9a2a-9b0b61e359c5)

![Screenshot_20240813_142839](https://github.com/user-attachments/assets/5af079a0-714a-47b3-8107-ac4b08af4092)

2024-08-13 14:23 UTC, maximevanhees commented
In the meanwhile I've tested on MacOS and there seems to be an issue with rendering the CSS, causing the application to look horrible. Will update ASAP.

2024-08-21 11:36 UTC, LeeSmet commented
@maximevanhees please rebase this branch on latest master since it's quite behind already. Additionally, in mycelium-ui/Cargo.toml, please fill in the metadata according to the other packages (author, version, license, etc).

2024-08-21 12:07 UTC, maximevanhees commented
> @maximevanhees please rebase this branch on latest master since it's quite behind already. Additionally, in mycelium-ui/Cargo.toml, please fill in the metadata according to the other packages (author, version, license, etc).

Should be all set now.

2024-08-21 14:46 UTC, maximevanhees commented on mycelium-ui/src/main.rs
> +}
As this was only used once in the application, I removed all the code related to `AppError` completely and changed it to just use `reqwest::Error`.

2024-08-21 14:46 UTC, maximevanhees commented on mycelium-ui/src/components/mod.rs
> +pub mod routes;
Fixed.

2024-08-21 14:46 UTC, maximevanhees commented on mycelium-ui/README.md
> +```
Updated.

2024-08-21 14:49 UTC, maximevanhees commented
@LeeSmet
The bundling does indeed fail even though we still get a working binary. I have found this issue online, but there seem to be no apparent fix yet.

https://github.com/tauri-apps/tauri/issues/749
https://github.com/DioxusLabs/dioxus/issues/2344

2024-08-21 15:17 UTC, maximevanhees commented
I have tested the bundling on Windows and there seems to be some error caused by an `Result::unwrap()` on a `Err` value from internal Dioxus code. It still managed to produce a working binary though. 

On MacOS the bundling works fine.

2024-08-22 08:03 UTC, LeeSmet requested changes
This PR looks good to go, except for some minor documentation nitpicks

2024-08-22 08:03 UTC, LeeSmet commented on mycelium-ui/README.md
> +This will start a development server and launch the application in your default webbrowser.
Is it really your default webbrowser? looks more like a webview

2024-08-26 11:18 UTC, LeeSmet approved these changes
LGTM :tada:

2024-08-26 11:18 UTC, merged